import { useState } from "react";
import {
  FileText, Version, Download, Share2, Edit3, ArrowRight, CheckCircle2,
  Copy, Eye, Sparkles, X, RotateCcw, Send
} from "lucide-react";
import { useAIEngine } from "../../context/AIEngineContext";
import { OutputArtifact } from "../../data/ai-engine-data";
import { motion, AnimatePresence } from "motion/react";
import { toast } from "sonner";

export function OutputsView() {
  const { outputs, activeContext, updateOutputVersion, requestActionApproval } = useAIEngine();

  const [selectedOutputModal, setSelectedOutputModal] = useState<OutputArtifact | null>(null);
  const [editingContent, setEditingContent] = useState("");
  const [changeSummary, setChangeSummary] = useState("");
  const [typeFilter, setTypeFilter] = useState("All");

  const filteredOutputs = outputs.filter((out) => {
    const matchesContext = out.contextId === activeContext.id;
    const matchesType = typeFilter === "All" || out.type === typeFilter;
    return matchesContext && matchesType;
  });

  const handleOpenEditor = (out: OutputArtifact) => {
    setSelectedOutputModal(out);
    setEditingContent(out.content);
    setChangeSummary("");
  };

  const handleSaveNewVersion = () => {
    if (!selectedOutputModal) return;
    updateOutputVersion(selectedOutputModal.id, editingContent, changeSummary || "User manual edit");
    setSelectedOutputModal(null);
  };

  const handleSendToHamraheSection = (out: OutputArtifact) => {
    requestActionApproval(
      `Send Output Artifact to ${out.targetHamraheSection || "Hamrahe Platform"}`,
      out.targetHamraheSection || "Primary Profile Section",
      out.dataSources,
      10,
      () => {
        toast.success(`Artifact "${out.title}" sent to ${out.targetHamraheSection}. Saved to section input.`);
      }
    );
  };

  return (
    <div className="space-y-6">
      {/* Header & Type Filters */}
      <div className="bg-white rounded-2xl p-5 border border-border/30 shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-lg font-bold text-foreground">Output Artifacts Library</h2>
          <p className="text-xs text-muted-foreground">
            Structured, versioned outputs generated by AI Engine and saved outside conversation chats.
          </p>
        </div>

        <select
          value={typeFilter}
          onChange={(e) => setTypeFilter(e.target.value)}
          className="text-xs bg-muted/50 border border-border/30 rounded-xl px-3 py-1.5 text-foreground cursor-pointer"
        >
          <option value="All">All Artifact Types</option>
          <option value="resume">Resumes</option>
          <option value="cover_letter">Cover Notes</option>
          <option value="profile_revision">Profile Revisions</option>
          <option value="hiring_criteria">Hiring Criteria</option>
          <option value="proposal">Project Proposals</option>
        </select>
      </div>

      {/* Artifacts Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filteredOutputs.map((out) => (
          <div
            key={out.id}
            className="bg-white rounded-2xl p-5 border border-border/30 shadow-sm hover:shadow-md transition-all flex flex-col justify-between gap-4"
          >
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-purple-100 text-purple-700 uppercase">
                  {out.type.replace(/_/g, " ")}
                </span>
                <span className="text-[10px] font-bold text-muted-foreground">Version {out.currentVersion}</span>
              </div>

              <h3 className="text-sm font-bold text-foreground">{out.title}</h3>
              <p className="text-xs text-muted-foreground line-clamp-3 font-mono bg-muted/20 p-2.5 rounded-xl border border-border/20">
                {out.content}
              </p>
            </div>

            <div className="space-y-2 pt-2 border-t border-border/20 text-xs">
              <div className="flex items-center justify-between text-[11px] text-muted-foreground">
                <span>Updated: {out.updatedAt}</span>
                <span className="font-semibold text-primary">{out.targetHamraheSection}</span>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleOpenEditor(out)}
                  className="flex-1 py-1.5 rounded-xl border border-border/40 text-xs font-semibold hover:bg-muted text-foreground flex items-center justify-center gap-1 cursor-pointer"
                >
                  <Edit3 className="w-3.5 h-3.5" />
                  <span>Edit / Version</span>
                </button>

                <button
                  onClick={() => handleSendToHamraheSection(out)}
                  className="py-1.5 px-3 rounded-xl bg-primary text-white text-xs font-bold hover:bg-primary/90 flex items-center gap-1 cursor-pointer shadow-xs"
                >
                  <Send className="w-3 h-3" />
                  <span>Send</span>
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* ARTIFACT EDITOR & VERSION HISTORY MODAL */}
      <AnimatePresence>
        {selectedOutputModal && (
          <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-3xl p-6 max-w-2xl w-full shadow-2xl border border-border/30 space-y-4 text-xs"
            >
              <div className="flex items-center justify-between">
                <div>
                  <span className="text-[10px] font-bold text-purple-600 uppercase">
                    Version {selectedOutputModal.currentVersion + 1} Editor
                  </span>
                  <h3 className="text-base font-bold text-foreground">{selectedOutputModal.title}</h3>
                </div>
                <button onClick={() => setSelectedOutputModal(null)} className="p-1 rounded-full hover:bg-muted">
                  <X className="w-5 h-5 text-muted-foreground" />
                </button>
              </div>

              <div className="space-y-2">
                <label className="font-bold text-foreground block">Artifact Content Text</label>
                <textarea
                  rows={8}
                  value={editingContent}
                  onChange={(e) => setEditingContent(e.target.value)}
                  className="w-full p-3 rounded-xl border border-border/30 font-mono bg-muted/20 text-xs focus:outline-none focus:ring-2 focus:ring-primary/20"
                />
              </div>

              <div>
                <label className="font-bold text-foreground block mb-1">Summary of Version Changes</label>
                <input
                  type="text"
                  value={changeSummary}
                  onChange={(e) => setChangeSummary(e.target.value)}
                  placeholder="e.g. Added Snapp design system experience bullets"
                  className="w-full p-2.5 rounded-xl border border-border/30 bg-muted/20 text-xs"
                />
              </div>

              <div className="space-y-2 pt-2 border-t border-border/20">
                <span className="font-bold text-foreground block">Version History</span>
                <div className="space-y-1.5 max-h-28 overflow-y-auto">
                  {selectedOutputModal.versions.map((ver) => (
                    <div key={ver.version} className="p-2 rounded-lg bg-muted/40 flex items-center justify-between text-[11px]">
                      <span className="font-bold text-foreground">Version {ver.version}</span>
                      <span className="text-muted-foreground">{ver.summaryOfChanges}</span>
                      <span className="text-muted-foreground">{ver.createdAt}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-2">
                <button
                  onClick={() => setSelectedOutputModal(null)}
                  className="px-4 py-2 rounded-xl border border-border/30 font-semibold"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSaveNewVersion}
                  className="px-5 py-2 rounded-xl bg-primary text-white font-bold hover:bg-primary/90 cursor-pointer"
                >
                  Save New Version
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
